### ISSUE TITLE
mvnd --status throws NumberFormatException in 0.0.9

### ISSUE THREAD

**Issue by odrotbohm** [mvndaemon/mvnd#147]
```
$ mvnd …
…
$ mvnd --status
                                    UUID      PID   Port   Status    RSS            Last activity  Java home
Exception in thread "main" java.lang.NumberFormatException: For input string: " 84276"
	at java.lang.Long.parseLong(Long.java:678)
	at java.lang.Long.parseLong(Long.java:817)
	at org.jboss.fuse.mvnd.common.OsUtils.findProcessRssInKb(OsUtils.java:59)
	at org.jboss.fuse.mvnd.client.DefaultClient.lambda$execute$0(DefaultClient.java:149)
	at java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.jboss.fuse.mvnd.client.DefaultClient.execute(DefaultClient.java:147)
	at org.jboss.fuse.mvnd.client.DefaultClient.main(DefaultClient.java:72)
```

Looks like there's a `String.trim()` missing?

**Comment by ppalaga** [comment]
Thanks for the report, @odrotbohm 

Which OS is that?

**Comment by odrotbohm** [comment]
MacOS.

**Comment by ppalaga** [comment]
Yeah, `.trim()` is not there. Let me add it. Strange that the test that we have for this is passing on GH Action's Catalina.

**Comment by ppalaga** [comment]
@odrotbohm you may want to test/use the package built by the CI https://github.com/mvndaemon/mvnd/suites/1398611867/artifacts/23216845 before we release.

**Comment by odrotbohm** [comment]
Playing with the snapshot build, looks like this is fixed. Thanks!
