### ISSUE TITLE
Upon installing release for Windows MVND not responsive

### ISSUE THREAD

**Issue by jaschenk** [mvndaemon/mvnd#152]
Upon installing release for Windows MVND not responsive and trying a simple:

$ mvnd --version
I had to hit enter key twice for response.
$ mvnd --version
Maven Daemon 0.0.10-windows-amd64 (native)
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\Users\JS33110\Tools\mvnd-0.0.10-windows-amd64\mvn
Java version: 14.0.2, vendor: AdoptOpenJDK, runtime: C:\Program Files\AdoptOpenJDK\jdk-14.0.2.12-hotspot
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

Then trying: 'mvnd clean package" I received:
$ mvnd clean package
[WARN] Environment mistmach !
[WARN] A few environment mismatches have been detected between the client and the daemon.
[WARN]    OLDPWD -> null instead of C:/Program Files/Git/
[WARN]    PWD -> C:/Program Files/Git/ instead of C:/Users/JS33110/code/NVE/seifnotificationsvc
[WARN] If the difference matters to you, stop the running daemons using mvnd --stop and
[WARN] start a new daemon from the current environment by issuing any mvnd build command.
[INFO] Scanning for projects...

Did a CNTRL-C to end.

Please advise.  Will attempt a stop and try again.

**Comment by gnodet** [comment]
Please ignore the warnings for now and see if there is an output of the maven build.

**Comment by jaschenk** [comment]
nothing there or moving.  Terminal input appears to have died in Git/Bash shell..

**Comment by gnodet** [comment]
You can check the logs in `[MVND_HOME]/daemon/` and see if the daemon prints something.

**Comment by jaschenk** [comment]
It just sits there for a mvnd clean package, then have to hit enter again and then see Starting a Daemon .... Scanning for projects.... And not other output.  I thought I would have at least seen the module status.  But must be running as a test email appeared from one of my tests.

Is the Terminal a child of the daemon process?  Hmm...  Thanks...  Will check output.  No issues on Linux of course ;)

**Comment by gnodet** [comment]
Yeah, the windows support is currently broken.  I'm trying to fix it...

**Comment by jaschenk** [comment]
This was found in the daemon log, if helpful:


09:23:22,992 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [C:\*******\mvnd-0.0.10-windows-amd64\mvn\conf\logging\logback.xml] at [file:/C:/Users/JS33110/Tools/mvnd-0.0.10-windows-amd64/mvn/conf/logging/logback.xml]
09:23:23,073 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
09:23:23,074 |-INFO in ch.qos.logback.classic.joran.action.LoggerContextListenerAction - Adding LoggerContextListener of type [ch.qos.logback.classic.jul.LevelChangePropagator] to the object stack
09:23:23,074 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@694e1548 - Propagating DEBUG level on Logger[ROOT] onto the JUL framework
09:23:23,083 |-INFO in ch.qos.logback.classic.joran.action.LoggerContextListenerAction - Starting LoggerContextListener
09:23:23,083 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [org.jboss.fuse.mvnd.logging.smart.ProjectBuildLogAppender]
09:23:23,083 |-ERROR in ch.qos.logback.core.joran.action.AppenderAction - Could not create an Appender of type [org.jboss.fuse.mvnd.logging.smart.ProjectBuildLogAppender]. ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type org.jboss.fuse.mvnd.logging.smart.ProjectBuildLogAppender
	at ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type org.jboss.fuse.mvnd.logging.smart.ProjectBuildLogAppender
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:69)
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:45)
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:34)
	at 	at ch.qos.logback.core.joran.action.AppenderAction.begin(AppenderAction.java:52)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callBeginAction(Interpreter.java:269)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:145)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:128)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:50)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
	at 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
	at 	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
	at 	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
	at 	at org.jboss.fuse.mvnd.common.Environment.<clinit>(Environment.java:57)
	at 	at org.jboss.fuse.mvnd.common.MavenDaemon.main(MavenDaemon.java:33)
Caused by: java.lang.ClassNotFoundException: org.jboss.fuse.mvnd.logging.smart.ProjectBuildLogAppender
	at 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:56)
	at 	... 22 common frames omitted
09:23:23,083 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@31:90 - ActionException in Action for tag [appender] ch.qos.logback.core.joran.spi.ActionException: ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type org.jboss.fuse.mvnd.logging.smart.ProjectBuildLogAppender
	at ch.qos.logback.core.joran.spi.ActionException: ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type org.jboss.fuse.mvnd.logging.smart.ProjectBuildLogAppender
	at 	at ch.qos.logback.core.joran.action.AppenderAction.begin(AppenderAction.java:76)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callBeginAction(Interpreter.java:269)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:145)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:128)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:50)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
	at 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
	at 	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
	at 	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
	at 	at org.jboss.fuse.mvnd.common.Environment.<clinit>(Environment.java:57)
	at 	at org.jboss.fuse.mvnd.common.MavenDaemon.main(MavenDaemon.java:33)
Caused by: ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type org.jboss.fuse.mvnd.logging.smart.ProjectBuildLogAppender
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:69)
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:45)
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:34)
	at 	at ch.qos.logback.core.joran.action.AppenderAction.begin(AppenderAction.java:52)
	at 	... 19 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.jboss.fuse.mvnd.logging.smart.ProjectBuildLogAppender
	at 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:56)
	at 	... 22 common frames omitted
09:23:23,083 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.FileAppender]
09:23:23,093 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [DAEMON]
09:23:23,104 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
09:23:23,173 |-INFO in ch.qos.logback.core.FileAppender[DAEMON] - File property is set to [C:\Users\JS33110\Tools\mvnd-0.0.10-windows-amd64/daemon/daemon-b0d50508-d0b0-4023-a4e8-7a367860d748.log]
09:23:23,179 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.jboss.fuse.mvnd.daemon] to DEBUG
09:23:23,179 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@694e1548 - Propagating DEBUG level on Logger[org.jboss.fuse.mvnd.daemon] onto the JUL framework
09:23:23,179 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [org.jboss.fuse.mvnd.daemon] to false
09:23:23,179 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [DAEMON] to Logger[org.jboss.fuse.mvnd.daemon]
09:23:23,180 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [Sisu] to INFO
09:23:23,180 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@694e1548 - Propagating INFO level on Logger[Sisu] onto the JUL framework
09:23:23,180 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.apache.maven.lifecycle.internal.builder.BuilderCommon] to ERROR
09:23:23,180 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@694e1548 - Propagating ERROR level on Logger[org.apache.maven.lifecycle.internal.builder.BuilderCommon] onto the JUL framework
09:23:23,181 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.eclipse.aether.internal.impl.WarnChecksumPolicy] to ERROR
09:23:23,181 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@694e1548 - Propagating ERROR level on Logger[org.eclipse.aether.internal.impl.WarnChecksumPolicy] onto the JUL framework
09:23:23,183 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
09:23:23,183 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@694e1548 - Propagating INFO level on Logger[ROOT] onto the JUL framework
09:23:23,183 |-ERROR in ch.qos.logback.core.joran.action.AppenderRefAction - Could not find an appender named [MEM]. Did you define it below instead of above in the configuration file?
09:23:23,183 |-ERROR in ch.qos.logback.core.joran.action.AppenderRefAction - See http://logback.qos.ch/codes.html#appender_order for more details.
09:23:23,183 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
09:23:23,185 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@711f39f9 - Registering current configuration as safe fallback point

**Comment by gnodet** [comment]
@jaschenk Could you try the latest CI build https://github.com/mvndaemon/mvnd/suites/1414215222/artifacts/23646901 ?

**Comment by jaschenk** [comment]
Hello,
unfortunately I tried the new snapshot, and got carbon-blacked to hell...
so no way to run a snapshot unfortunately.

Jeff

**Comment by ppalaga** [comment]
We have released 0.0.11 in between: https://github.com/mvndaemon/mvnd/releases/tag/0.0.11 Could you please try that one?

**Comment by jaschenk** [comment]
Sorry, due to corporate I am unable to run and not approved due to
carbon-black flagging.

Will use on linux but not on WIN...

**Comment by ppalaga** [comment]
Closed as stale. Please re-open if the issue still occurs with mvnd 0.4.2
