### ISSUE TITLE
Problem with the native client running in Cygwin

### ISSUE THREAD

**Issue by gnodet** [mvndaemon/mvnd#156]
```
gnodet@GUILLAUMENO0AC9 /cygdrive/c/Users/gnodet/mvnd
$ /cygdrive/c/mvnd-0.0.11-SNAPSHOT-windows-amd64/bin/mvnd.exe -v
Maven Daemon 0.0.11-SNAPSHOT-windows-amd64 (native)
Terminal: org.jline.terminal.impl.jansi.win.JansiWinSysTerminal
Exception in thread "main" java.lang.RuntimeException: Could not get a real path from path \cygdrive\c\graalvm-ce-java11-20.2.0
        at org.jboss.fuse.mvnd.common.Environment.findJavaHome(Environment.java:107)
        at org.jboss.fuse.mvnd.client.ClientLayout.getEnvInstance(ClientLayout.java:100)
        at org.jboss.fuse.mvnd.client.DefaultClient.execute(DefaultClient.java:150)
        at org.jboss.fuse.mvnd.client.DefaultClient.main(DefaultClient.java:74)
```

**Comment by gnodet** [comment]
I think we need to have the equivalent in native mode to the line https://github.com/mvndaemon/mvnd/blob/8f322e7b0ba05dfd7e8037fcb8e0ced58f7a21ce/dist/src/main/distro/bin/mvnd.sh#L114
