### ISSUE TITLE
exec-maven-plugin fails to run maven wrapper when run via maven daemon

### ISSUE THREAD

**Issue by filiphr** [mvndaemon/mvnd#171]
On Twitter I [commented](https://twitter.com/filiphr/status/1320846772353249282) that there might be some kind of skipping of plugins or phases. However, I was wrong. The problem I had was due to something else.

For some reason when using the exec-maven-plugin to run the maven wrapper it fails due to a missing file.

I created [this](https://github.com/filiphr/maven-daemon-problem-reproducal) repository to try to show the problem. It is using maven assembly to create some packages which it then builds them with maven and downloads the artifacts in a local folder.

There is a readme there. In any case, to see the problem execute the following steps:

* `cd assembly`
* `mvnd package`

There will be an error that there is no such file or directory when the `build-demo-package` execution runs.
There is no problem when running this with `mvn package`.
If you change the `executable` from `../mvnw` to `mvn` in the `assembly/pom.xml` then everything runs fine with `mvnd package` as well.

My output of `mvnd -v` is:

>Maven Daemon 0.0.10-darwin-amd64 (native)
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: \~/.sdkman/candidates/mvnd/current/mvn
Java version: 11.0.7, vendor: AdoptOpenJDK, runtime:\~/.sdkman/candidates/java/11.0.7.hs-adpt
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.6", arch: "x86_64", family: "mac"

**Comment by gnodet** [comment]
@filiphr just tried it, but it seems to work correctly for me.

**Comment by filiphr** [comment]
That is extremely weird, I tried it again today and it indeed works. 

Yesterday I was constantly having

{quote}
[INFO] --- exec-maven-plugin:3.0.0:exec (build-demo-package) @ maven-daemon-assembly ---
[ERROR] Command execution failed.
java.io.IOException: Cannot run program "../mvnw" (in directory "~/projects_oss/maven-daemon-problem/assembly/target/demo-0.0.1-SNAPSHOT-demo"): error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at java.base/java.lang.Runtime.exec(Runtime.java:592)
	at org.apache.commons.exec.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:61)
	at org.apache.commons.exec.DefaultExecutor.launch(DefaultExecutor.java:279)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:336)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:982)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:929)
	at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:457)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.jboss.fuse.mvnd.builder.SmartBuilderImpl.buildProject(SmartBuilderImpl.java:174)
	at org.jboss.fuse.mvnd.builder.SmartBuilderImpl$ProjectBuildTask.run(SmartBuilderImpl.java:194)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 21 common frames omitted
{quote}


I can't explain what changed between yesterday and today. I'll close this issue. Sorry for the noise.
