### ISSUE TITLE
Do not create runtime files/directories in installation directory

### ISSUE THREAD

**Issue by mikaelstaldal** [mvndaemon/mvnd#179]
mvnd 0.0.11 creates a `daemon` directory in the installation directory, which does not work if you install it in a system directory (like `/opt` or `/usr/local`) and let it be own by root:

```
$ mvnd
Exception in thread "main" org.jboss.fuse.mvnd.common.DaemonException: java.nio.file.AccessDeniedException: /opt/mvnd-0.0.11-linux-amd64/daemon
        at org.jboss.fuse.mvnd.common.DaemonRegistry.<init>(DaemonRegistry.java:81)
        at org.jboss.fuse.mvnd.client.DefaultClient.execute(DefaultClient.java:151)
        at org.jboss.fuse.mvnd.client.DefaultClient.main(DefaultClient.java:74)
Caused by: java.nio.file.AccessDeniedException: /opt/mvnd-0.0.11-linux-amd64/daemon
        at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389)
        at java.nio.file.Files.createDirectory(Files.java:689)
        at java.nio.file.Files.createAndCheckIsDirectory(Files.java:796)
        at java.nio.file.Files.createDirectories(Files.java:782)
        at org.jboss.fuse.mvnd.common.DaemonRegistry.<init>(DaemonRegistry.java:74)
        ... 2 more
```

It should create runtime files/directories in `/tmp` if they do not need to survive reboot, or otherwise in `$HOME/.cache`.

**Comment by gnodet** [comment]
Using `$HOME/.mvnd/daemon` sounds reasonable to me.

**Comment by famod** [comment]
AFAICT, depending on which files actually end up there, different `mvnd` installations would need to be taken into account.

**Comment by gnodet** [comment]
@famod you mean different mvnd versions ? I don't think I see a use case for having a user installing the same mvnd version in different multiple times.

**Comment by ppalaga** [comment]
I think we need distinct registries per mvnd version.

**Comment by famod** [comment]
@gnodet See https://github.com/mvndaemon/mvnd/issues/122#issuecomment-715606048

**Comment by gnodet** [comment]
> @gnodet See [#122 (comment)](https://github.com/mvndaemon/mvnd/issues/122#issuecomment-715606048)

Ok, but I still haven't understood the use case.  I'm refactoring the daemon settings handling so that it will be easier to add properties passed to the daemon, and also make all those properties part of the daemon selection process.
I'll also add support for specifying more than one daemon property file for configuration (global, user, local).
This mean that any difference in the daemon properties will mean using a different daemon.

Is configuration your use case for using different installations ?

**Comment by gnodet** [comment]
And for the local maven repository, I think it should currently be already working. I.e. the daemon should not messed up the different repositories.  However, it also means it won't cache anything when switching from one repo to another, so we could investigate making the local repo a discriminating property too.

**Comment by gnodet** [comment]
This has been done as part of https://github.com/mvndaemon/mvnd/commit/4030f8b5a4e27e6693de7249bee3f0f7d2293db3

The default is `${USER.HOME}/.mvnd/v${version}/` but it can be changed using the `mvnd.daemon.storage` property to point to a different location.
