### ISSUE TITLE
NoClassDefFoundError: org.slf4j.LoggerFactory

### ISSUE THREAD

**Issue by oowekyala** [mvndaemon/mvnd#200]
I just installed mvnd through sdkman on ubuntu 18.04. Upon starting the first daemon I get the following error:
```
Exception in thread "main" org.jboss.fuse.mvnd.common.DaemonException$ConnectException: Timeout waiting to connect to the Maven daemon.
Daemon uid: 0c2ce1ff-c72f-4952-8ece-7507e6aa91d1
  no log file at: /home/clem/.sdkman/candidates/mvnd/0.0.11/daemon/daemon-0c2ce1ff-c72f-4952-8ece-7507e6aa91d1.log
  output: /home/clem/.sdkman/candidates/mvnd/0.0.11/daemon/daemon-0c2ce1ff-c72f-4952-8ece-7507e6aa91d1.out.log
----- Last  20 lines from daemon output - /home/clem/.sdkman/candidates/mvnd/0.0.11/daemon/daemon-0c2ce1ff-c72f-4952-8ece-7507e6aa91d1.out.log -----
Exception in thread "main" java.lang.NoClassDefFoundError: org.slf4j.LoggerFactory
	at org.jboss.fuse.mvnd.common.Environment.<clinit>(Environment.java:67)
	at org.jboss.fuse.mvnd.common.MavenDaemon.main(MavenDaemon.java:33)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:766)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1078)
	... 2 more
----- End of the daemon output -----

	at org.jboss.fuse.mvnd.client.DaemonConnector.startDaemon(DaemonConnector.java:240)
	at org.jboss.fuse.mvnd.client.DaemonConnector.connect(DaemonConnector.java:110)
	at org.jboss.fuse.mvnd.client.DefaultClient.execute(DefaultClient.java:205)
	at org.jboss.fuse.mvnd.client.DefaultClient.main(DefaultClient.java:74)
```

Looks like this is related to

https://github.com/mvndaemon/mvnd/commit/a805c07a3156db7bf8ce3908b2c12426f2ce4f4b#diff-5e7ca06bb080c44c53988d2094f5979680272b3526d2dea059df8e78e06875e8R70

the class name in this error message has dots instead of slashes.  Also I was previously using mvnd `0.0.10` which worked fine

Probably related to my jdk version:
```
openjdk 11.0.8 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.21.0, JRE 11 Linux amd64-64-Bit Compressed References 20200715_697 (JIT enabled, AOT enabled)
OpenJ9   - 34cf4c075
OMR      - 113e54219
JCL      - 95bb504fbb based on jdk-11.0.8+10)
```

It works fine on jdk 1.8

**Comment by gnodet** [comment]
If the culprit is correct, it should already have been fixed by https://github.com/mvndaemon/mvnd/commit/4030f8b5a4e27e6693de7249bee3f0f7d2293db3#diff-5e7ca06bb080c44c53988d2094f5979680272b3526d2dea059df8e78e06875e8L89-L109

You can try with a recent snapshot https://github.com/mvndaemon/mvnd/runs/1381357139 (on the _Artifacts_ link)

**Comment by oowekyala** [comment]
This snapshot version works, thanks :)
