### ISSUE TITLE
Exit code not propagated from the daemon to mvnd client

### ISSUE THREAD

**Issue by ppalaga** [mvndaemon/mvnd#220]
Calling `cl.execute(output, "clean", "install", "-e", "-B").assertSuccess();` in [NewManagedModuleNativeIT](https://github.com/ppalaga/mvnd/blob/i218.t/integration-tests/src/test/java/org/mvndaemon/mvnd/it/NewManagedModuleNativeIT.java#L87) should be enough to make the test fail. But it is not. There is apparently some exception thrown in the daemon, but the deamon exception handlers are not catching it. It looks like the exception belongs to a different class loader then the exception handlers. 

Here is the daemon exception stack trace: 

```
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:397)
	at org.apache.maven.graph.DefaultGraphBuilder.collectProjects(DefaultGraphBuilder.java:414)
	at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor(DefaultGraphBuilder.java:405)
	at org.apache.maven.graph.DefaultGraphBuilder.build(DefaultGraphBuilder.java:82)
	at org.apache.maven.DefaultMaven.buildGraph(DefaultMaven.java:507)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:219)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.DaemonMavenCli.execute(DaemonMavenCli.java:651)
	at org.apache.maven.cli.DaemonMavenCli.doMain(DaemonMavenCli.java:193)
	at org.apache.maven.cli.DaemonMavenCli.main(DaemonMavenCli.java:175)
	at org.mvndaemon.mvnd.daemon.Server.handle(Server.java:532)
	at org.mvndaemon.mvnd.daemon.Server.client(Server.java:242)
	at org.mvndaemon.mvnd.daemon.Server.accept(Server.java:217)
	at java.base/java.lang.Thread.run(Thread.java:834)'}
```

Steps to reproduce are the same as in https://github.com/mvndaemon/mvnd/issues/218

**Comment by ppalaga** [comment]
No, the root cause is that we swallow the int result of `org.apache.maven.cli.DaemonMavenCli.main(List<String>, String, String, Map<String, String>)` which is the actual exit code. Let me fix it,
