### ISSUE TITLE
No reuse of daemons - error on daemon creation - unknown signal TSTP (Windows 10, Bellsoft Liberica JDK)

### ISSUE THREAD

**Issue by Archangel1C** [mvndaemon/mvnd#260]
When running mvnd commands under windows with Bellsoft Liberica JDK, mvnd always creates a new daemon - the old ones are shown as "incompatible" or "stopped". The daemon log file shows an error `Unknown signal: TSTP` on creation of `org.mvndaemon.mvnd.daemon.Server`.

Note: it works f.i. with "Java version: 1.8.0_161, vendor: Oracle Corporation", so perhaps it's only the non-Oracle (OpenJDK?) ones, that don't work.

Test commands:
```
> mvnd --version
mvnd native client 0.1.1-windows-amd64 (6e0a08b1700b4fa1278ae8734f895a598bca263b)
Terminal: org.jline.terminal.impl.jansi.win.JansiWinSysTerminal
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\Program Files (noinst)\javautil\mvnd\mvn
Java version: 1.8.0_202, vendor: BellSoft, runtime: C:\Program Files\Java\jdk8u202 (Liberica)\jre
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

> mvnd --version
mvnd native client 0.1.1-windows-amd64 (6e0a08b1700b4fa1278ae8734f895a598bca263b)
Terminal: org.jline.terminal.impl.jansi.win.JansiWinSysTerminal
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\Program Files (noinst)\javautil\mvnd\mvn
Java version: 1.8.0_202, vendor: BellSoft, runtime: C:\Program Files\Java\jdk8u202 (Liberica)\jre
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

> mvnd --status
                                    UUID      PID   Port   Status    RSS            Last activity  Java home
    9aa84b9f-9eac-48d1-9829-5d77e8dc161f     9388  58319     Idle   102m  2020-12-13T21:49:03.669  C:\Program Files\Java\jdk8u202 (Liberica)\jre
    4ad65c3c-77fd-48ea-9778-8488d03916b0    18012  58313     Idle   102m  2020-12-13T21:48:53.691  C:\Program Files\Java\jdk8u202 (Liberica)\jre
```
StackTrace:
```
==> %userprofile%\.m2\mvnd\registry\0.1.1\daemon-4ad65c3c-77fd-48ea-9778-8488d03916b0.log <==
21:48:51.319 W Unable to ignore INT and TSTP signals
java.lang.IllegalArgumentException: Unknown signal: TSTP
        at sun.misc.Signal.<init>(Signal.java:143)
        at org.mvndaemon.mvnd.daemon.Server.<init>(Server.java:105)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.mvndaemon.mvnd.common.MavenDaemon.main(MavenDaemon.java:75)
```

[registry.zip](https://github.com/mvndaemon/mvnd/files/5685423/registry.zip)
[daemon-4ad65c3c-77fd-48ea-9778-8488d03916b0.log](https://github.com/mvndaemon/mvnd/files/5685424/daemon-4ad65c3c-77fd-48ea-9778-8488d03916b0.log)
[daemon-9aa84b9f-9eac-48d1-9829-5d77e8dc161f.log](https://github.com/mvndaemon/mvnd/files/5685425/daemon-9aa84b9f-9eac-48d1-9829-5d77e8dc161f.log)

**Comment by ppalaga** [comment]
Thanks for the report, the fix is underway.
