### ISSUE TITLE
A new daemon is always started with OpenJDK 8

### ISSUE THREAD

**Issue by LeBezout** [mvndaemon/mvnd#266]
Hi,

Is there a known issue with Java versions lower than 11 ?

With Open JDK 8 I always obtain the following message :

```
$mvnd --version
Starting new daemon, X incompatible and Y stopped daemons could not be reused, ...
```

This furtive message doesn't appear with open JDK 11.

Reproduced on Windows 10 (mvnd-0.1.1-windows-amd64) & Linux Centos 7 or Ubuntu 20.04 (mvnd-0.1.1-linux-amd64).

First lines of log in Centos 7 :

```
11:51:38.662 D Initializing daemon with properties:
     mvnd.noDaemon=false
     mvnd.debug=false
     mvnd.idleTimeout=3h
     mvnd.keepAlive=100ms
     mvnd.extClasspath=
     mvnd.coreExtensions=
     mvnd.minHeapSize=128M
     mvnd.maxHeapSize=2G
     mvnd.jvmArgs=
     mvnd.enableAssertions=false
     mvnd.expirationCheckDelay=10s
     mvnd.duplicateDaemonGracePeriod=10s

11:51:38.667 I Daemon started
11:51:38.669 D daemon is running. Sleeping until state changes.
11:51:38.694 I Client connected
11:51:38.698 I Waiting for request
11:51:38.702 I Request received: [...]
```

in Windows 10 :

```
09:45:34.813 W Unable to ignore INT and TSTP signals
java.lang.IllegalArgumentException: Unknown signal: TSTP
	at java.base/jdk.internal.misc.Signal.<init>(Signal.java:148)
	at jdk.unsupported/sun.misc.Signal.<init>(Signal.java:139)
	at org.mvndaemon.mvnd.daemon.Server.<init>(Server.java:105)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.mvndaemon.mvnd.common.MavenDaemon.main(MavenDaemon.java:75)
09:45:35.906 D Initializing daemon with properties:
     mvnd.noDaemon=false
     mvnd.debug=false
     mvnd.idleTimeout=3h
     mvnd.keepAlive=100ms
     mvnd.extClasspath=
     mvnd.coreExtensions=
     mvnd.minHeapSize=128M
     mvnd.maxHeapSize=2G
     mvnd.jvmArgs=
     mvnd.enableAssertions=false
     mvnd.expirationCheckDelay=10s
     mvnd.duplicateDaemonGracePeriod=10s

09:45:35.914 I Daemon started
09:45:35.915 D daemon is running. Sleeping until state changes.
09:45:36.018 I Client connected
09:45:36.741 I Waiting for request
09:45:36.746 I Request received: [...]
```

**Comment by LeBezout** [comment]
Shame on me, duplicate from #261

**Comment by gnodet** [comment]
The fact that TSTP or INT signals can't be registered should not causeany problem. I'll enhance the warning to explain.
So it should be unrelated to the daemon not being reused, unless you actually hit `Ctrl+C` or `Ctrl+Z` in the client, which would cause the daemon to die.

**Comment by ppalaga** [comment]
Thanks for the report anyway, @LeBezout. Your report brought the most of details that helped me to find out that we have solved [this exact problem in the past](https://github.com/mvndaemon/mvnd/issues/65) already but the fix disappeared through some refactoring.
