### ISSUE TITLE
Crash with Java 17

### ISSUE THREAD

**Issue by slachiewicz** [mvndaemon/mvnd#272]
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.mvndaemon.mvnd.common.MavenDaemon.main(MavenDaemon.java:75)
Caused by: java.lang.IllegalAccessError: class org.mvndaemon.mvnd.common.DaemonRegistry (in unnamed module @0x38e79ae3) cannot access class sun.nio.ch.DirectBuffer (in module java.base) because module java.base does not export sun.nio.ch to unnamed module @0x38e79ae3
	at org.mvndaemon.mvnd.common.DaemonRegistry.compareAndSwapLong(DaemonRegistry.java:473)
	at org.mvndaemon.mvnd.common.DaemonRegistry.tryLockNanos8a(DaemonRegistry.java:419)
	at org.mvndaemon.mvnd.common.DaemonRegistry.tryLockNanosLong(DaemonRegistry.java:377)
	at org.mvndaemon.mvnd.common.DaemonRegistry.busyLockLong(DaemonRegistry.java:346)
	at org.mvndaemon.mvnd.common.DaemonRegistry.doUpdate(DaemonRegistry.java:231)
	at org.mvndaemon.mvnd.common.DaemonRegistry.update(DaemonRegistry.java:223)
	at org.mvndaemon.mvnd.common.DaemonRegistry.store(DaemonRegistry.java:208)
	at org.mvndaemon.mvnd.daemon.Server.<init>(Server.java:139)
	... 6 more

**Comment by ppalaga** [comment]
Interesting, thanks for the report. We have recently changed how the registry is changed. Would you plz try to reproduce with a recent CI build, e.g. this one? https://github.com/mvndaemon/mvnd/actions/runs/423338455#artifacts

**Comment by slachiewicz** [comment]
Yes, it works correctly - thx for fixing.

**Comment by ppalaga** [comment]
For the record, this should have been fixed by 73dec36 available in mvnd version 0.2.0
