### ISSUE TITLE
mvnd 0.2.0 can no longer resolve our Artifactory server (works for 0.1.1 in same shell)

### ISSUE THREAD

**Issue by ftrossbach** [mvndaemon/mvnd#274]
Steps to reproduce (using sdkman):

1. `sdk use mvnd 0.1.1`
2. `mvnd clean package` (results in success)
3. `sdk use mvnd 0.2.0`
4. `mvnd clean package` (results in "Name or service not known")

Full error (anonymized):

`Failed to execute goal on project myproject: Could not resolve dependencies for project myproject: Failed to collect dependencies at some-internal-dependency: Failed to read artifact descriptor for some-internal-dependency: Could not transfer artifact some-internal-dependency from/to artifactory.my-org.org (https://artifactory.my-org.org/artifactory/releases-snapshots-virtual): Transfer failed for https://artifactory.myorg.org/artifactory/releases-snapshots-virtual/some-internal-dependency.pom: Unknown host artifactory.my-org.org: Name or service not known`

It's truly weird

`Caused by: java.net.UnknownHostException: artifactory.my-org.org: Name or service not known
	at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:929)
	at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1515)
	at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848)
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1505)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1364)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1298)
	at org.apache.maven.wagon.providers.http.httpclient.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.maven.wagon.providers.http.httpclient.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
	at org.apache.maven.wagon.providers.http.httpclient.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
	at org.apache.maven.wagon.providers.http.httpclient.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.maven.wagon.providers.http.httpclient.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.maven.wagon.providers.http.httpclient.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.maven.wagon.providers.http.httpclient.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.maven.wagon.providers.http.httpclient.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.maven.wagon.providers.http.wagon.shared.AbstractHttpClientWagon.execute(AbstractHttpClientWagon.java:1002)
	at org.apache.maven.wagon.providers.http.wagon.shared.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:1160)
	... 40 common frames omitted
`

**Comment by ftrossbach** [comment]
As colleagues cannot reproduce, it must be me...
