### ISSUE TITLE
Compilation fails when using a plugin and try to provide additional dependencies to that plugin

### ISSUE THREAD

**Issue by lucamolteni** [mvndaemon/mvnd#276]
See the reproducer here https://github.com/lucamolteni/mvnd-plugin-reproducer

The bootstrap module is a simple maven plugin that generates a class in generated-sources

The startup module uses this plugin and print the constant generated in the class

This fails with `mvnd clean install` but runs with `mvn clean install`

```
mvn clean install
java -cp startup/target/java -cp startup/target/startup-1.0.0-SNAPSHOT.jar org.reproducer.MainClass```
```

By removing this section in startup module

```
<!-- the following is used to provide a SLF4j binding to the ValidationBootstrapMain and related CP. Set src/test/resources/logback.xml root to DEBUG for debugging -->
<includePluginDependencies>true</includePluginDependencies>
<additionalClasspathElements>
    <additionalClasspathElement>${project.basedir}/src/test/resources/</additionalClasspathElement>
</additionalClasspathElements>
```

Everything works

cc @tarilabs

**Comment by gnodet** [comment]
Fwiw, it fails only the second time.

**Comment by lucamolteni** [comment]
@gnodet any news? I'd love to use `mvnd` in Drools 

Thanks for the great product!

**Comment by gnodet** [comment]
> @gnodet any news? I'd love to use `mvnd` in Drools
> 
> Thanks for the great product!

I found a way to make the test actually reproductible. 
However, this looks rather a bug in the maven-compiler-plugin .

Here's the log when the compiler fails:
```
ProjectLogMessage{projectId='startup', message='[DEBUG] Using compiler 'javac'.'}
ProjectLogMessage{projectId='startup', message='[DEBUG] Adding /Users/gnodet/work/git/mvnd/integration-tests/target/mvnd-tests/BootstrapPluginTest/project/startup/target/generated-sources/annotations to compile source roots:
  /Users/gnodet/work/git/mvnd/integration-tests/target/mvnd-tests/BootstrapPluginTest/project/startup/src/main/java
  /Users/gnodet/work/git/mvnd/integration-tests/target/mvnd-tests/BootstrapPluginTest/project/startup/target/generated-sources/bootstrap'}
ProjectLogMessage{projectId='startup', message='[DEBUG] New compile source roots:
  /Users/gnodet/work/git/mvnd/integration-tests/target/mvnd-tests/BootstrapPluginTest/project/startup/src/main/java
  /Users/gnodet/work/git/mvnd/integration-tests/target/mvnd-tests/BootstrapPluginTest/project/startup/target/generated-sources/bootstrap
  /Users/gnodet/work/git/mvnd/integration-tests/target/mvnd-tests/BootstrapPluginTest/project/startup/target/generated-sources/annotations'}
ProjectLogMessage{projectId='startup', message='[DEBUG] CompilerReuseStrategy: reuseCreated'}
ProjectLogMessage{projectId='startup', message='[DEBUG] useIncrementalCompilation enabled'}
ProjectLogMessage{projectId='startup', message='[DEBUG] Stale source detected: /Users/gnodet/work/git/mvnd/integration-tests/target/mvnd-tests/BootstrapPluginTest/project/startup/src/main/java/org/reproducer/MainClass.java'}
ProjectLogMessage{projectId='startup', message='[DEBUG] Stale source detected: /Users/gnodet/work/git/mvnd/integration-tests/target/mvnd-tests/BootstrapPluginTest/project/startup/target/generated-sources/bootstrap/org/reproducer/Model.java'}
ProjectLogMessage{projectId='startup', message='[INFO] Changes detected - recompiling the module!'}
ProjectLogMessage{projectId='startup', message='[DEBUG] Classpath:'}
ProjectLogMessage{projectId='startup', message='[DEBUG]  /Users/gnodet/work/git/mvnd/integration-tests/target/mvnd-tests/BootstrapPluginTest/project/startup/target/classes'}
ProjectLogMessage{projectId='startup', message='[DEBUG]  /Users/gnodet/work/git/mvnd/integration-tests/target/mvnd-tests/BootstrapPluginTest/project/bootstrap/target/bootstrap-1.0.0-SNAPSHOT.jar'}
ProjectLogMessage{projectId='startup', message='[DEBUG] Source roots:'}
ProjectLogMessage{projectId='startup', message='[DEBUG]  /Users/gnodet/work/git/mvnd/integration-tests/target/mvnd-tests/BootstrapPluginTest/project/startup/src/main/java'}
ProjectLogMessage{projectId='startup', message='[DEBUG]  /Users/gnodet/work/git/mvnd/integration-tests/target/mvnd-tests/BootstrapPluginTest/project/startup/target/generated-sources/bootstrap'}
ProjectLogMessage{projectId='startup', message='[DEBUG]  /Users/gnodet/work/git/mvnd/integration-tests/target/mvnd-tests/BootstrapPluginTest/project/startup/target/generated-sources/annotations'}
ProjectLogMessage{projectId='startup', message='[DEBUG] Command line options:'}
ProjectLogMessage{projectId='startup', message='[DEBUG] -d /Users/gnodet/work/git/mvnd/integration-tests/target/mvnd-tests/BootstrapPluginTest/project/startup/target/classes -classpath /Users/gnodet/work/git/mvnd/integration-tests/target/mvnd-tests/BootstrapPluginTest/project/startup/target/classes:/Users/gnodet/work/git/mvnd/integration-tests/target/mvnd-tests/BootstrapPluginTest/project/bootstrap/target/bootstrap-1.0.0-SNAPSHOT.jar: -sourcepath /Users/gnodet/work/git/mvnd/integration-tests/target/mvnd-tests/BootstrapPluginTest/project/startup/src/main/java:/Users/gnodet/work/git/mvnd/integration-tests/target/mvnd-tests/BootstrapPluginTest/project/startup/target/generated-sources/annotations: -s /Users/gnodet/work/git/mvnd/integration-tests/target/mvnd-tests/BootstrapPluginTest/project/startup/target/generated-sources/annotations -g -nowarn -target 11 -source 11'}
ProjectLogMessage{projectId='startup', message='[WARN] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!'}
ProjectLogMessage{projectId='startup', message='[DEBUG] incrementalBuildHelper#beforeRebuildExecution'}
ProjectLogMessage{projectId='startup', message='[INFO] Compiling 1 source file to /Users/gnodet/work/git/mvnd/integration-tests/target/mvnd-tests/BootstrapPluginTest/project/startup/target/classes'}
ProjectLogMessage{projectId='startup', message='[DEBUG] incrementalBuildHelper#afterRebuildExecution'}
ProjectLogMessage{projectId='startup', message='[INFO] -------------------------------------------------------------'}
ProjectLogMessage{projectId='startup', message='[ERROR] COMPILATION ERROR : '}
ProjectLogMessage{projectId='startup', message='[INFO] -------------------------------------------------------------'}
ProjectLogMessage{projectId='startup', message='[ERROR] /Users/gnodet/work/git/mvnd/integration-tests/target/mvnd-tests/BootstrapPluginTest/project/startup/src/main/java/org/reproducer/MainClass.java:[22,43] cannot find symbol
  symbol:   class Model
  location: package org.reproducer'}
ProjectLogMessage{projectId='startup', message='[INFO] 1 error'}
```

As we can see, when the compiler command line is created, the `target/generated-sources/bootstrap` is missing for some reason...

**Comment by gnodet** [comment]
Here's a trimmed thread dump when the problem happens:
```
"Thread-0@3298" daemon prio=5 tid=0x12 nid=NA waiting
  java.lang.Thread.State: WAITING
	  at jdk.internal.misc.Unsafe.park(Unsafe.java:-1)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
	  at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:433)
	  at org.mvndaemon.mvnd.builder.ProjectExecutorService.take(ProjectExecutorService.java:84)
	  at org.mvndaemon.mvnd.builder.SmartBuilderImpl.build(SmartBuilderImpl.java:102)
	  at org.mvndaemon.mvnd.builder.SmartBuilder.build(SmartBuilder.java:113)
	  - locked <0x1a6c> (a org.mvndaemon.mvnd.builder.SmartBuilder)
	  at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	  at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	  at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	  at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	  at org.apache.maven.cli.DaemonMavenCli.execute(DaemonMavenCli.java:730)
	  at org.apache.maven.cli.DaemonMavenCli.doMain(DaemonMavenCli.java:225)
	  at org.apache.maven.cli.DaemonMavenCli.main(DaemonMavenCli.java:203)
	  at org.mvndaemon.mvnd.daemon.Server.handle(Server.java:565)
	  at org.mvndaemon.mvnd.daemon.Server.client(Server.java:257)
	  at org.mvndaemon.mvnd.daemon.Server.accept(Server.java:225)
	  at org.mvndaemon.mvnd.daemon.Server$$Lambda$113.1392271025.run(Unknown Source:-1)
	  at java.lang.Thread.run(Thread.java:829)

"BuilderThread 2@6681" daemon prio=5 tid=0x86 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at org.apache.maven.plugin.compiler.AbstractCompilerMojo.removeEmptyCompileSourceRoots(AbstractCompilerMojo.java:1548)
	  at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:586)
	  at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:187)
	  at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	  at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	  at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	  at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	  at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	  at org.mvndaemon.mvnd.builder.SmartBuilderImpl.buildProject(SmartBuilderImpl.java:178)
	  at org.mvndaemon.mvnd.builder.SmartBuilderImpl$ProjectBuildTask.run(SmartBuilderImpl.java:198)
	  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	  at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	  at java.lang.Thread.run(Thread.java:829)

"org.reproducer.BootstrapMain.main()@6682" daemon prio=5 tid=0x87 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at sun.nio.fs.UnixNativeDispatcher.access0(UnixNativeDispatcher.java:-1)
	  at sun.nio.fs.UnixNativeDispatcher.access(UnixNativeDispatcher.java:481)
	  at sun.nio.fs.UnixFileSystemProvider.checkAccess(UnixFileSystemProvider.java:311)
	  at java.nio.file.Files.createDirectories(Files.java:762)
	  at org.reproducer.BootstrapMain.main(BootstrapMain.java:45)
	  at java.lang.invoke.LambdaForm$DMH.1175072806.invokeStaticInit(LambdaForm$DMH:-1)
	  at java.lang.invoke.LambdaForm$MH.1968853583.invoke_MT(LambdaForm$MH:-1)
	  at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:254)
	  at java.lang.Thread.run(Thread.java:829)
```

The problem is that the exec plugin and the compiler are somewhat running concurrently and when the compiler checks the existence of the source directories, the plugin hasn't created the directories yet...

**Comment by gnodet** [comment]
So the problem seems more located in the `exec-maven-plugin`, where in this case, the mojo returns without the thread having finished the job.

**Comment by gnodet** [comment]
So the following patch seems to fix the problem:
```
diff --git a/daemon/src/main/java/org/mvndaemon/mvnd/daemon/Server.java b/daemon/src/main/java/org/mvndaemon/mvnd/daemon/Server.java
index 99b3826..ead2ecc 100644
--- a/daemon/src/main/java/org/mvndaemon/mvnd/daemon/Server.java
+++ b/daemon/src/main/java/org/mvndaemon/mvnd/daemon/Server.java
@@ -214,7 +214,6 @@ public class Server implements AutoCloseable, Runnable {
     static class DaemonThread extends Thread {
         public DaemonThread(Runnable target) {
             super(target);
-            setDaemon(true);
         }
     }
 
(END)
```

However, I need to double check if that could cause other problems...
