### ISSUE TITLE
[ENHANCEMENT] mvnd failed while I purposely disabled ~/.m2 directory

### ISSUE THREAD

**Issue by yiding-he** [mvndaemon/mvnd#278]
I purposely disabled read/write access to `~/.m2` directory and set `<localRepository>` to other location to prevent any downloading of jars to my home directory. Maven works fine but mvnd fails:

```
Exception in thread "main" org.mvndaemon.mvnd.common.DaemonException: java.nio.file.AccessDeniedException: C:\Users\yidin\.m2\mvnd
        at org.mvndaemon.mvnd.common.DaemonRegistry.<init>(DaemonRegistry.java:79)
        at org.mvndaemon.mvnd.client.DefaultClient.execute(DefaultClient.java:171)
        at org.mvndaemon.mvnd.client.DefaultClient.main(DefaultClient.java:98)
Caused by: java.nio.file.AccessDeniedException: C:\Users\yidin\.m2\mvnd
        at sun.nio.fs.WindowsFileSystemProvider.createDirectory(WindowsFileSystemProvider.java:509)
        at java.nio.file.Files.createDirectory(Files.java:689)
        at java.nio.file.Files.createAndCheckIsDirectory(Files.java:796)
        at java.nio.file.Files.createDirectories(Files.java:782)
        at org.mvndaemon.mvnd.common.DaemonRegistry.<init>(DaemonRegistry.java:72)
        ... 2 more
```

So I think what I need is for mvnd to ignore this failure and print a warning message instead.

**Comment by ppalaga** [comment]
Failure to create the `DaemonRegistry` cannot be ignored because it is vital for the daemon. You can pass an alternative registry location via `-Dmvnd.daemonStorage=/some/writable/path` on the command line or by adding `mvnd.daemonStorage=/some/writable/path` to `/.m2/mvnd.properties`. Does that help?

**Comment by yiding-he** [comment]
Seems it works, thanks!
![qiniML1Se9](https://user-images.githubusercontent.com/900606/102765846-28a6de00-43b8-11eb-9817-9ad71c990f9f.png)
