### ISSUE TITLE
[ERROR] Multiple entries with same key

### ISSUE THREAD

**Issue by gunnarmorling** [mvndaemon/mvnd#333]
When trying to build [Layrry](https://github.com/moditect/layrry) with mvnd, I'm getting this error:

```
[ERROR] Multiple entries with same key: com.example.it:it-greeter=0 and com.example.it:it-greeter=0
java.lang.IllegalArgumentException: Multiple entries with same key: com.example.it:it-greeter=0 and com.example.it:it-greeter=0
	at com.google.common.collect.RegularImmutableMap.createHashTable(RegularImmutableMap.java:104)
	at com.google.common.collect.RegularImmutableMap.create(RegularImmutableMap.java:74)
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:338)
	at org.mvndaemon.mvnd.builder.ReactorBuildStats.create(ReactorBuildStats.java:70)
	at org.mvndaemon.mvnd.builder.SmartBuilderImpl.<init>(SmartBuilderImpl.java:79)
	at org.mvndaemon.mvnd.builder.SmartBuilder.build(SmartBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.DaemonMavenCli.execute(DaemonMavenCli.java:667)
	at org.apache.maven.cli.DaemonMavenCli.doMain(DaemonMavenCli.java:212)
	at org.apache.maven.cli.DaemonMavenCli.main(DaemonMavenCli.java:190)
	at org.mvndaemon.mvnd.daemon.Server.handle(Server.java:530)
	at org.mvndaemon.mvnd.daemon.Server.client(Server.java:243)
	at org.mvndaemon.mvnd.daemon.Server.accept(Server.java:218)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

I suppose it's due to multiple versions of that greeter module being part of the reactor build. This works just fine with regular Maven.

**Comment by gunnarmorling** [comment]
Wow, that was quick. Thanks!

>
