### ISSUE TITLE
Build failing with a NPE

### ISSUE THREAD

**Issue by galegofer** [mvndaemon/mvnd#372]
After having the project building properly, I suddenly started having this error (no changes where made at config, I am at 0.4.1):

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.709 s (Wall Clock)
[INFO] Finished at: 2021-03-08T08:58:50+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] NullPointerException
java.lang.NullPointerException: null
        at org.mvndaemon.mvnd.cache.invalidating.InvalidatingProjectArtifactsCache$Record.getDependencyPaths(InvalidatingProjectArtifactsCache.java:48)
        at org.mvndaemon.mvnd.cache.impl.WatchServiceCacheFactory$WrappedCacheRecord.getDependencyPaths(WatchServiceCacheFactory.java:254)
        at org.mvndaemon.mvnd.cache.impl.WatchServiceCacheFactory.add(WatchServiceCacheFactory.java:75)
        at org.mvndaemon.mvnd.cache.impl.WatchServiceCacheFactory$WatchServiceCache.put(WatchServiceCacheFactory.java:210)
        at org.mvndaemon.mvnd.cache.invalidating.InvalidatingProjectArtifactsCache.put(InvalidatingProjectArtifactsCache.java:90)
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:248)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:202)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.mvndaemon.mvnd.builder.SmartBuilderImpl.buildProject(SmartBuilderImpl.java:178)
        at org.mvndaemon.mvnd.builder.SmartBuilderImpl$ProjectBuildTask.run(SmartBuilderImpl.java:198)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
[ERROR] Party Proxy: null: NullPointerException
java.lang.RuntimeException: Party Proxy: null
        at org.mvndaemon.mvnd.builder.SmartBuilderImpl.buildProject(SmartBuilderImpl.java:183)
        at org.mvndaemon.mvnd.builder.SmartBuilderImpl$ProjectBuildTask.run(SmartBuilderImpl.java:198)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException: null
        at org.mvndaemon.mvnd.cache.invalidating.InvalidatingProjectArtifactsCache$Record.getDependencyPaths(InvalidatingProjectArtifactsCache.java:48)
        at org.mvndaemon.mvnd.cache.impl.WatchServiceCacheFactory$WrappedCacheRecord.getDependencyPaths(WatchServiceCacheFactory.java:254)
        at org.mvndaemon.mvnd.cache.impl.WatchServiceCacheFactory.add(WatchServiceCacheFactory.java:75)
        at org.mvndaemon.mvnd.cache.impl.WatchServiceCacheFactory$WatchServiceCache.put(WatchServiceCacheFactory.java:210)
        at org.mvndaemon.mvnd.cache.invalidating.InvalidatingProjectArtifactsCache.put(InvalidatingProjectArtifactsCache.java:90)
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:248)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:202)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.mvndaemon.mvnd.builder.SmartBuilderImpl.buildProject(SmartBuilderImpl.java:178)
        ... 6 common frames omitted
[ERROR]

**Comment by ppalaga** [comment]
Sounds like https://github.com/mvndaemon/mvnd/issues/347 - please check whether the stack trace is really the same. Stock `mvn` would perhaps show a more meaningful exception. There is a fix in master and we should release within a couple of days.

**Comment by ppalaga** [comment]
Could you please try with 0.4.2?

**Comment by galegofer** [comment]
Tried with 0.4.3, working. Thanks!
