### ISSUE TITLE
noDaemon not supported in native mode

### ISSUE THREAD

**Issue by rmannibucau** [mvndaemon/mvnd#374]
```
$ mvnd install -Dmvnd.noDaemon=true
Exception in thread "main" java.lang.UnsupportedOperationException: The mvnd.noDaemon property is not supported in native mode.
	at org.mvndaemon.mvnd.client.DaemonConnector.connectNoDaemon(DaemonConnector.java:126)
	at org.mvndaemon.mvnd.client.DaemonConnector.connect(DaemonConnector.java:93)
	at org.mvndaemon.mvnd.client.DefaultClient.execute(DefaultClient.java:245)
	at org.mvndaemon.mvnd.client.DefaultClient.main(DefaultClient.java:112)
```

Would be great to have at least a fallback not "leaking" a daemon when used (even if it is about starting a daemon and killing it at the end)

**Comment by gnodet** [comment]
What's your use case for using this option ? My original purpose was to ease debugging, but since you want to use it in native mode, I suspect yours is different ...

**Comment by rmannibucau** [comment]
Mvnd brings more than just mvn without the daemon, like better defaults to cite just one thing.
In some cases I dont want to leak the daemon (consumes too much mem for me in some cases)
Installed with sdkman it is native so unifying both options would be nice.

**Comment by delanym** [comment]
With Maven wrapper I have to choose either mvn or mvnd. I don't want to force users either way.

**Comment by gnodet** [comment]
> With Maven wrapper I have to choose either mvn or mvnd. I don't want to force users either way.

You choose the tool (maven vs any other build system) and the version of the tool used, but you don't want to force the user between _mvn_ and _mvnd_. Why ?

**Comment by delanym** [comment]
mvnd requires at least another 1Gb of always-on memory

**Comment by gnodet** [comment]
> mvnd requires at least another 1Gb of always-on memory

Makes sense.  I totally agree with the idea of spawning a daemon and not keeping it alive if the `mvnd.noDaemon` option is set.  It should just be a matter of spawning a daemon, passing the `mvnd.noDaemon` option and handle it correctly in the daemon after the build (i.e. letting the process die).
