### ISSUE TITLE
Segmentation fault on startup after updating to 0.4.2

### ISSUE THREAD

**Issue by VoidAspect** [mvndaemon/mvnd#375]
The output of the `--version` command (full error log in attachment [hs_err_pid4797.log](https://github.com/mvndaemon/mvnd/files/6134468/hs_err_pid4797.log))

```
~ $ mvnd --version
mvnd native client 0.4.2-linux-amd64 (7d488f2c97680fde41508d9442edeabc583ac600)
Terminal: org.jline.terminal.impl.PosixSysTerminal with pty org.jline.terminal.impl.jansi.linux.LinuxNativePty
Exception in thread "main" org.mvndaemon.mvnd.common.DaemonException$ConnectException: Could not receive a message from the daemon.
Daemon id: 7e27b065
  log file: /home/void/.m2/mvnd/registry/0.4.2/daemon-7e27b065.log
----- Last  200 lines from daemon log file - /home/void/.m2/mvnd/registry/0.4.2/daemon-7e27b065.log -----
11:21:48.771 D Initializing daemon with properties:
     mvnd.noDaemon=false
     mvnd.debug=false
     mvnd.idleTimeout=3h
     mvnd.keepAlive=100ms
     mvnd.extClasspath=
     mvnd.coreExtensions=
     mvnd.minHeapSize=128M
     mvnd.maxHeapSize=2G
     mvnd.enableAssertions=false
     mvnd.expirationCheckDelay=10s
     mvnd.duplicateDaemonGracePeriod=10s

11:21:48.775 I Daemon started
11:21:48.776 D daemon is running. Sleeping until state changes.
11:21:48.903 I Client connected
11:21:48.916 I Waiting for request
11:21:48.931 I Request received: BuildRequest{args=[--version, -Dstyle.color=always, -T, 11, -b, smart, -Dmvnd.terminalWidth=255], workingDir='/home/void', projectDir='/home/void'}
11:21:48.943 I Executing request
----- End of the daemon log file -----
  output: /home/void/.m2/mvnd/registry/0.4.2/daemon-7e27b065.out.log
----- Last  200 lines from daemon output - /home/void/.m2/mvnd/registry/0.4.2/daemon-7e27b065.out.log -----
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.maven.cli.DaemonMavenCli (file:/home/void/.sdkman/candidates/mvnd/0.4.2/mvn/lib/ext/mvnd-daemon-0.4.2.jar) to field java.lang.ProcessEnvironment.theEnvironment
WARNING: Please consider reporting this to the maintainers of org.apache.maven.cli.DaemonMavenCli
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007eff21287461, pid=4797, tid=4821
#
# JRE version: OpenJDK Runtime Environment AdoptOpenJDK (15.0.2+7) (build 15.0.2+7)
# Java VM: OpenJDK 64-Bit Server VM AdoptOpenJDK (15.0.2+7, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0x7e4461]  java_lang_String::utf8_length(oopDesc*, typeArrayOopDesc*)+0x31
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P %E" (or dumping to /home/void/core.4797)
#
# An error report file with more information is saved as:
# /home/void/hs_err_pid4797.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/AdoptOpenJDK/openjdk-support/issues
#
----- End of the daemon output -----

	at org.mvndaemon.mvnd.client.DaemonClientConnection.receive(DaemonClientConnection.java:127)
	at org.mvndaemon.mvnd.client.DefaultClient.execute(DefaultClient.java:269)
	at org.mvndaemon.mvnd.client.DefaultClient.main(DefaultClient.java:112)
Caused by: java.io.IOException: No message received within 3000ms, daemon may have crashed. You may want to check its status using mvnd --status
	at org.mvndaemon.mvnd.client.DaemonClientConnection.receive(DaemonClientConnection.java:111)
	... 2 more
```

**Comment by VoidAspect** [comment]
Looks like it this only happens why use JDK 15 - no such problem JDK 11

**Comment by gnodet** [comment]
The problem seems to come from `chdir`
```
Stack: [0x0000700006a39000,0x0000700006b39000],  sp=0x0000700006b38600,  free space=1021k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.dylib+0x4be69b]  _ZN16java_lang_String11utf8_lengthEP7oopDescP16typeArrayOopDesc+0x1b
V  [libjvm.dylib+0x52826d]  jni_GetStringUTFChars+0x10d
C  [jansi-2.3.1-1e11e4fdac18046f-libjansi.jnilib+0x11a8]  Java_org_fusesource_jansi_internal_CLibrary_chdir+0x1c
j  org.fusesource.jansi.internal.CLibrary.chdir(Ljava/lang/String;)I+0
j  org.apache.maven.cli.DaemonMavenCli.environment(Ljava/lang/String;Ljava/util/Map;)V+164
j  org.apache.maven.cli.DaemonMavenCli.doMain(Lorg/apache/maven/cli/CliRequest;Ljava/util/Map;)I+21
j  org.apache.maven.cli.DaemonMavenCli.main(Ljava/util/List;Ljava/lang/String;Ljava/lang/String;Ljava/util/Map;Lorg/mvndaemon/mvnd/logging/smart/BuildEventListener;)I+59
j  org.mvndaemon.mvnd.daemon.Server.handle(Lorg/mvndaemon/mvnd/common/DaemonConnection;Lorg/mvndaemon/mvnd/common/Message$BuildRequest;)V+141
j  org.mvndaemon.mvnd.daemon.Server.client(Ljava/nio/channels/SocketChannel;)V+137
j  org.mvndaemon.mvnd.daemon.Server.accept()V+10
j  org.mvndaemon.mvnd.daemon.Server$$Lambda$132+0x0000000800d8a3a0.run()V+4
j  java.lang.Thread.run()V+11 java.base@15.0.2
v  ~StubRoutines::call_stub
V  [libjvm.dylib+0x4bc0b2]  _ZN9JavaCalls11call_helperEP9JavaValueRK12methodHandleP17JavaCallArgumentsP6Thread+0x2e2
V  [libjvm.dylib+0x4baf99]  _ZN9JavaCalls12call_virtualEP9JavaValueP5KlassP6SymbolS5_P17JavaCallArgumentsP6Thread+0x1e9
V  [libjvm.dylib+0x4bb063]  _ZN9JavaCalls12call_virtualEP9JavaValue6HandleP5KlassP6SymbolS6_P6Thread+0x63
V  [libjvm.dylib+0x569970]  _ZL12thread_entryP10JavaThreadP6Thread+0xb0
V  [libjvm.dylib+0xa21152]  _ZN10JavaThread17thread_main_innerEv+0xb2
V  [libjvm.dylib+0xa1e221]  _ZN6Thread8call_runEv+0x71
V  [libjvm.dylib+0x8404a7]  _ZL19thread_native_entryP6Thread+0x197
C  [libsystem_pthread.dylib+0x6950]  _pthread_start+0xe0
C  [libsystem_pthread.dylib+0x247b]  thread_start+0xf
```

**Comment by gnodet** [comment]
Using `mvnd -v -Dmvnd.jvmArgs="-Xcheck:jni"` leads to
```
FATAL ERROR in native method: JNI string operation received a non-string
	at org.fusesource.jansi.internal.CLibrary.chdir(Native Method)
	at org.apache.maven.cli.DaemonMavenCli.environment(DaemonMavenCli.java:673)
	at org.apache.maven.cli.DaemonMavenCli.doMain(DaemonMavenCli.java:213)
	at org.apache.maven.cli.DaemonMavenCli.main(DaemonMavenCli.java:203)
	at org.mvndaemon.mvnd.daemon.Server.handle(Server.java:533)
	at org.mvndaemon.mvnd.daemon.Server.client(Server.java:242)
	at org.mvndaemon.mvnd.daemon.Server.accept(Server.java:217)
	at org.mvndaemon.mvnd.daemon.Server$$Lambda$132/0x0000000800d8a3a0.run(Unknown Source)
	at java.lang.Thread.run(java.base@15.0.2/Thread.java:832)
```

**Comment by gnodet** [comment]
This should be fixed with https://github.com/fusesource/jansi/commit/629fdafae88a1b468b9d43f6d9cd30cebc881ff5
