### ISSUE TITLE
mvnd fails if there is no .mvn/ dir in the user home

### ISSUE THREAD

**Issue by tadayosi** [mvndaemon/mvnd#42]
Right after `mvnd --install`, mvnd fails with the following error:
```
$ mvnd --version
Maven Daemon 0.0.0 (native)
Exception in thread "main" java.lang.IllegalStateException: Could not detect maven.multiModuleProjectDirectory by climbing up from [/home/tasato] seeking a .mvn directory. You may want to create a .mvn directory in the root directory of your source tree.
	at org.jboss.fuse.mvnd.client.Environment.lambda$findMultiModuleProjectDirectory$4(Environment.java:127)
	at org.jboss.fuse.mvnd.client.Environment$EnvValue.get(Environment.java:246)
	at org.jboss.fuse.mvnd.client.Environment$EnvValue.asPath(Environment.java:258)
	at org.jboss.fuse.mvnd.client.Environment.findMultiModuleProjectDirectory(Environment.java:131)
	at org.jboss.fuse.mvnd.client.ClientLayout.getEnvInstance(ClientLayout.java:45)
	at org.jboss.fuse.mvnd.client.DefaultClient.lambda$main$0(DefaultClient.java:69)
	at org.jboss.fuse.mvnd.client.DefaultClient.execute(DefaultClient.java:170)
	at org.jboss.fuse.mvnd.client.DefaultClient.main(DefaultClient.java:69)
```
Manually creating a directory `.mvn/` in the user home solves the error, but it's handy if mvnd auto resolves it.

**Comment by ppalaga** [comment]
Yeah, I admit it's not especially robust, but we basically mimic, what stock Maven does in `mvn.[sh|cmd]`. The only substantial difference is that while Maven can do without `maven.multiModuleProjectDirectory` we cannot (or maybe we could?).

> it's handy if mvnd auto resolves it.

I wonder how? I do not think we can reliably autodetect the top level directory of any random multimodule project.

**Comment by tadayosi** [comment]
I thought that mvnd could just `mkdir $HOME/.mvn` if it doesn't exist. Not sure if it's a silly hack or not though.

**Comment by gnodet** [comment]
@tadayosi there's a misunderstanding here.  `mvnd` is looking for `[project]/.mvn` dir to detect the root directory of a multiproject module, not `$HOME/.mvn`.

**Comment by ppalaga** [comment]
No, `.mvn` directory is supposed to mark the root of a multimodule maven project and we cannot know where it is. The bottom line is that `mvnd --version` shouldn't really require a maven project at all.

**Comment by tadayosi** [comment]
Thanks for the explanation. So there are a couple of suggestions here:

1. Make `mvnd --version` (and possibly other non-project general options) not rely on `.mvn/`
2. For project-related commands, show more use-friendly message in the absence of `.mvn/` tracing the dir hierarchy
