### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException during tests

### ISSUE THREAD

**Issue by gnodet** [mvndaemon/mvnd#433]
```
2021-06-16T14:28:25.8870320Z java.lang.ArrayIndexOutOfBoundsException: Index 61 out of bounds for length 6
2021-06-16T14:28:25.8873080Z 	at org.mvndaemon.mvnd.common.DaemonRegistry.doUpdate(DaemonRegistry.java:195)
2021-06-16T14:28:25.8876700Z 	at org.mvndaemon.mvnd.common.DaemonRegistry.read(DaemonRegistry.java:160)
2021-06-16T14:28:25.8878460Z 	at org.mvndaemon.mvnd.common.DaemonRegistry.get(DaemonRegistry.java:97)
2021-06-16T14:28:25.8880770Z 	at org.mvndaemon.mvnd.client.DaemonConnector.connectToDaemonWithId(DaemonConnector.java:406)
2021-06-16T14:28:25.8896890Z 	at org.mvndaemon.mvnd.client.DaemonConnector.startDaemon(DaemonConnector.java:287)
2021-06-16T14:28:25.8899220Z 	at org.mvndaemon.mvnd.client.DaemonConnector.connect(DaemonConnector.java:121)
2021-06-16T14:28:25.8901340Z 	at org.mvndaemon.mvnd.client.DefaultClient.execute(DefaultClient.java:245)
2021-06-16T14:28:25.9004740Z 	at org.mvndaemon.mvnd.junit.JvmTestClient.execute(JvmTestClient.java:34)
2021-06-16T14:28:25.9107380Z 	at org.mvndaemon.mvnd.client.Client.execute(Client.java:27)
2021-06-16T14:28:25.9147940Z 	at org.mvndaemon.mvnd.it.EnvironmentTest.cleanInstall(EnvironmentTest.java:53)
2021-06-16T14:28:25.9150220Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-06-16T14:28:25.9152800Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-06-16T14:28:25.9155130Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-06-16T14:28:25.9156980Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-06-16T14:28:25.9158510Z 	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:686)
2021-06-16T14:28:25.9160850Z 	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
2021-06-16T14:28:25.9163470Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
2021-06-16T14:28:25.9166510Z 	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
2021-06-16T14:28:25.9169490Z 	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
2021-06-16T14:28:25.9172570Z 	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
2021-06-16T14:28:25.9175570Z 	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
2021-06-16T14:28:25.9177990Z 	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
2021-06-16T14:28:25.9180730Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
2021-06-16T14:28:25.9183700Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
2021-06-16T14:28:25.9186950Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
2021-06-16T14:28:25.9190100Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
2021-06-16T14:28:25.9192660Z 	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
2021-06-16T14:28:25.9194970Z 	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
2021-06-16T14:28:25.9197670Z 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:205)
2021-06-16T14:28:25.9201190Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2021-06-16T14:28:25.9204540Z 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:201)
2021-06-16T14:28:25.9207890Z 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:137)
2021-06-16T14:28:25.9221110Z 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:71)
2021-06-16T14:28:25.9223970Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
2021-06-16T14:28:25.9226840Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2021-06-16T14:28:25.9229650Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
2021-06-16T14:28:25.9231900Z 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
2021-06-16T14:28:25.9234360Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
2021-06-16T14:28:25.9237270Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2021-06-16T14:28:25.9240260Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
2021-06-16T14:28:25.9243070Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
2021-06-16T14:28:25.9244900Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
2021-06-16T14:28:25.9248120Z 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
2021-06-16T14:28:25.9252430Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
2021-06-16T14:28:25.9257260Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2021-06-16T14:28:25.9260080Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
2021-06-16T14:28:25.9262360Z 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
2021-06-16T14:28:25.9265010Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
2021-06-16T14:28:25.9268040Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2021-06-16T14:28:25.9271160Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
2021-06-16T14:28:25.9273970Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
2021-06-16T14:28:25.9275580Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
2021-06-16T14:28:25.9278750Z 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
2021-06-16T14:28:25.9282730Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
2021-06-16T14:28:25.9285590Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2021-06-16T14:28:25.9288450Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
2021-06-16T14:28:25.9290700Z 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
2021-06-16T14:28:25.9293000Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
2021-06-16T14:28:25.9295850Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2021-06-16T14:28:25.9298840Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
2021-06-16T14:28:25.9301660Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
2021-06-16T14:28:25.9320520Z 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
2021-06-16T14:28:25.9326100Z 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
2021-06-16T14:28:25.9329450Z 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
2021-06-16T14:28:25.9331990Z 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
2021-06-16T14:28:25.9333890Z 	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
2021-06-16T14:28:25.9336170Z 	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
2021-06-16T14:28:25.9338580Z 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
2021-06-16T14:28:25.9341900Z 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
2021-06-16T14:28:25.9344820Z 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150)
2021-06-16T14:28:25.9347740Z 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124)
2021-06-16T14:28:25.9350540Z 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
2021-06-16T14:28:25.9353500Z 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
2021-06-16T14:28:25.9355960Z 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
2021-06-16T14:28:25.9362540Z 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

**Comment by gnodet** [comment]
Full log
[1_darwin.txt](https://github.com/mvndaemon/mvnd/files/6667934/1_darwin.txt)

**Comment by gnodet** [comment]
This is similar to #432 and mvnd should try to recover if possible.
