### ISSUE TITLE
`IllegalStateException` on multi module project failure

### ISSUE THREAD

**Issue by andreyrmg** [mvndaemon/mvnd#486]
```
[ERROR] COMPILATION ERROR :                                                                                            
[ERROR] <some-source>.java:[564,24] error: ';' expected
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project <some-project>: Compilation failure
[ERROR] <some-source>.java:[564,24] error: ';' expected
[ERROR] 
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project <some-project>: Compilation failure
<some-source>.java:[564,24] error: ';' expected

	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:215)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.mvndaemon.mvnd.builder.SmartBuilderImpl.buildProject(SmartBuilderImpl.java:178)
	at org.mvndaemon.mvnd.builder.SmartBuilderImpl$ProjectBuildTask.run(SmartBuilderImpl.java:198)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
<some-source>.java:[564,24] error: ';' expected

	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1220)
	at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:187)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	... 10 common frames omitted
[ERROR] Unexpected message type 24: ExecutionFailure{projectId='<some-project>', halted=true, exception='org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project <some-project>: Compilation failure
[ERROR] <some-source>.java:[564,24] error: ';' expected
[ERROR] '}
java.lang.IllegalStateException: Unexpected message type 24: ExecutionFailure{projectId='<some-project>', halted=true, exception='org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project <some-project>: Compilation failure
<some-source>.java:[564,24] error: ';' expected
'}
	at org.mvndaemon.mvnd.common.Message.getClassOrder(Message.java:163)
	at java.util.Comparator.lambda$comparingInt$7b0bb60$1(Comparator.java:490)
	at java.util.Comparator.lambda$thenComparing$36697e65$1(Comparator.java:216)
	at java.util.concurrent.PriorityBlockingQueue.siftUpUsingComparator(PriorityBlockingQueue.java:374)
	at java.util.concurrent.PriorityBlockingQueue.offer(PriorityBlockingQueue.java:491)
	at java.util.concurrent.PriorityBlockingQueue.add(PriorityBlockingQueue.java:463)
	at org.mvndaemon.mvnd.daemon.ClientDispatcher.projectStarted(ClientDispatcher.java:86)
	at org.mvndaemon.mvnd.logging.smart.LoggingExecutionListener.projectSkipped(LoggingExecutionListener.java:107)
	at org.apache.maven.lifecycle.internal.DefaultExecutionEventCatapult.fire(DefaultExecutionEventCatapult.java:68)
	at org.apache.maven.lifecycle.internal.DefaultExecutionEventCatapult.fire(DefaultExecutionEventCatapult.java:42)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:100)
	at org.mvndaemon.mvnd.builder.SmartBuilderImpl.buildProject(SmartBuilderImpl.java:178)
	at org.mvndaemon.mvnd.builder.SmartBuilderImpl$ProjectBuildTask.run(SmartBuilderImpl.java:198)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

This error is not stable. It depends on how many messages are in the queue at the time of the method `org.mvndaemon.mvnd.daemon.ClientDispatcher#executionFailure` call.

So the root problem is that method `org.mvndaemon.mvnd.common.Message#getClassOrder` doesn't support  `EXECUTION_FAILURE` type.

**Comment by gnodet** [comment]
Fixed, thx !
