### ISSUE TITLE
Could not notify CliPluginRealmCache

### ISSUE THREAD

**Issue by orpiske** [mvndaemon/mvnd#49]
Sorry for opening a vague report like this, but I couldn't really figure out what went wrong. 

One of my builds succeeded, but nonetheless printed a message like this: 

```
[WARN] Could not notify CliPluginRealmCache
java.nio.file.NoSuchFileException: /Users/otavio/Projects/java/camel-kafka-connector/buildingtools/target/test-classes
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixPath.toRealPath(UnixPath.java:860)
	at org.jboss.fuse.mvnd.plugin.CliPluginRealmCache$1.onEvent(CliPluginRealmCache.java:455)
	at org.apache.maven.eventspy.internal.EventSpyDispatcher.onEvent(EventSpyDispatcher.java:104)
	at org.apache.maven.cli.DaemonMavenCli.execute(DaemonMavenCli.java:490)
	at org.apache.maven.cli.DaemonMavenCli.doMain(DaemonMavenCli.java:175)
	at org.jboss.fuse.mvnd.daemon.Server.handle(Server.java:420)
	at org.jboss.fuse.mvnd.daemon.Server.client(Server.java:194)
	at org.jboss.fuse.mvnd.daemon.Server.lambda$accept$1(Server.java:175)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

I built [the project](https://github.com/apache/camel-kafka-connector/) it using `mvnd -DskipIntegrationTests=true clean install` on a Mac. 

If there's something I could do to try to collect more information, I would be happy to try it.

**Comment by ppalaga** [comment]
Thanks for the report, I think it is quite clear what is going on.

**Comment by ppalaga** [comment]
There is no test for the fix. Would you mind testing with master? If it works for you @gnodet might consider a release (I am leaving for PTO now).

**Comment by orpiske** [comment]
> There is no test for the fix. Would you mind testing with master? If it works for you @gnodet might consider a release (I am leaving for PTO now).

Thanks for the fix @ppalaga. I tried running with master but I couldn't make it running. I tried a few different things, like manually installing the client on `$HOME/.m2/mvnd/0.0.1/lib/ext/mvnd-client-0.1.0-SNAPSHOT.jar`.

I'll definitely try w/ the next version once it's out, though.

**Comment by ppalaga** [comment]
To test the master, please do the following:

* Build as documented in the readme: https://github.com/mvndaemon/mvnd#build-mvnd-from-source
* Remove any existing `mvnd` binaries from your `PATH` (eg. by renaming them)
* Add `<MVND_SOURCE_ROOT>/client/target/mvnd` to `PATH`
* Change `mvn.home` in  `~/.m2/mvnd.properties` to `<MVND_SOURCE_ROOT>/daemon/target/maven-distro`
* Chech that `mvnd -v` shows a -SNAPSHOT version
* Perform your scenario to verify the fix for the current issue.

**Comment by orpiske** [comment]
@ppalaga sorry for the late reply, it's been a busy week. I just wanted to share a feedback that the the code fix worked and I don't have that issue anymore. Thanks!
