### ISSUE TITLE
Unsupported address error when running linux machine

### ISSUE THREAD

**Issue by yliu224** [mvndaemon/mvnd#514]
I am trying to run this project on a linux machine but I got this error. Should I enable ipv6 or something?

```
❯ mvnd-0.7.0-linux-amd64/bin/mvnd clean install
Exception in thread "main" java.lang.IllegalArgumentException: Unsupported address: inet:/[0:0:0:0:0:0:0:1]:34269
        at org.mvndaemon.mvnd.common.SocketFamily.fromString(SocketFamily.java:95)
	at org.mvndaemon.mvnd.client.DaemonConnector.connect(DaemonConnector.java:482)
	at org.mvndaemon.mvnd.client.DaemonConnector.connectToDaemon(DaemonConnector.java:452)
	at org.mvndaemon.mvnd.client.DaemonConnector.connectToDaemonWithId(DaemonConnector.java:438)
	at org.mvndaemon.mvnd.client.DaemonConnector.startDaemon(DaemonConnector.java:288)
	at org.mvndaemon.mvnd.client.DaemonConnector.connect(DaemonConnector.java:122)
	at org.mvndaemon.mvnd.client.DefaultClient.execute(DefaultClient.java:269)
	at org.mvndaemon.mvnd.client.DefaultClient.main(DefaultClient.java:117)
```

**Comment by ppalaga** [comment]
A wild guess: Maybe your daemon somehow observes `java.net.preferIPv4Stack=true` (see https://docs.oracle.com/javase/7/docs/api/java/net/doc-files/net-properties.html ) but you have only an IPv6 address defined for localhost in your `/etc/hosts`?

**Comment by ppalaga** [comment]
Here is my `/etc/hosts` FWIW:

```
$ cat /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4 terpistone.localdomain
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6 terpistone.localdomain
```

**Comment by yliu224** [comment]
Here is mine 

```
❯ cat hosts
# Do not remove the following lines, or various programs that require network
# functionality will fail.
127.0.0.1 localhost localhost.localdomain localhost4 localhost4.localdomain4
::1 localhost localhost.localdomain localhost6 localhost6.localdomain6
```

**Comment by yliu224** [comment]
> A wild guess: Maybe your daemon somehow observes `java.net.preferIPv4Stack=true` (see https://docs.oracle.com/javase/7/docs/api/java/net/doc-files/net-properties.html ) but you have only an IPv6 address defined for localhost in your `/etc/hosts`?

Can I override this settings somewhere?

**Comment by yliu224** [comment]
I see where my issue is. I have a environment parameter set up like this 

```
-Xmx8192m -Djava.net.preferIPv4Stack=false -Djava.net.preferIPv6Addresses=true
```

**Comment by ppalaga** [comment]
Could you please check whether it would work when you:

* Keep `-Djava.net.preferIPv4Stack=false -Djava.net.preferIPv6Addresses=true` in the env of the daemon as you had it before and 
* Pass `-Djava.net.preferIPv4Stack=false -Djava.net.preferIPv6Addresses=true` on the commandline when invoking `mvnd`, e.g. `mvnd -Djava.net.preferIPv4Stack=false -Djava.net.preferIPv6Addresses=true -v`

**Comment by yliu224** [comment]
Yes, it's the same 

```
❯ mvnd -Djava.net.preferIPv4Stack=false -Djava.net.preferIPv6Addresses=true -v
mvnd native client 0.7.1-linux-amd64 (97c587c11383a67b5bd0ff8388bd94c694b91c1e)
Terminal: org.jline.terminal.impl.PosixSysTerminal with pty org.jline.terminal.impl.jansi.linux.LinuxNativePty
Exception in thread "main" java.lang.IllegalArgumentException: Unsupported address: inet:/[0:0:0:0:0:0:0:1]:38953
	at org.mvndaemon.mvnd.common.SocketFamily.fromString(SocketFamily.java:95)
	at org.mvndaemon.mvnd.client.DaemonConnector.connect(DaemonConnector.java:482)
	at org.mvndaemon.mvnd.client.DaemonConnector.connectToDaemon(DaemonConnector.java:452)
	at org.mvndaemon.mvnd.client.DaemonConnector.connectToDaemonWithId(DaemonConnector.java:438)
	at org.mvndaemon.mvnd.client.DaemonConnector.startDaemon(DaemonConnector.java:288)
	at org.mvndaemon.mvnd.client.DaemonConnector.connect(DaemonConnector.java:122)
	at org.mvndaemon.mvnd.client.DefaultClient.execute(DefaultClient.java:272)
	at org.mvndaemon.mvnd.client.DefaultClient.main(DefaultClient.java:118)
❯ echo $JAVA_TOOL_OPTIONS
-Xmx8192m -Djava.net.preferIPv6Addresses=true
```

**Comment by yliu224** [comment]
Found the work around. Just unset the environment parameter first then pass the parameter in the command line.
1. ```❯  unset JAVA_TOOL_OPTIONS```
2. ```❯  mvnd -Djava.net.preferIPv4Stack=false -Djava.net.preferIPv6Addresses=true -v```
